### ISSUE TITLE
Issue to install it in linux

### ISSUE THREAD

**Issue by liuqianhn** [WGLab/epilepsy-autism-PPI-network#1]
As asked by Prof. Wang, I tested the installation in CHOP HPC.  It seems that many packages in `environment.yml` are specific to Mac. It would be great to provide OS-independent `environment.yml`.

**Comment by loafyyy** [comment]
Thanks for the comment. I updated `environment.yml` so it should work on Linux now. I was able to create the environment in CHOP HPC, but you can double-check again.
